version: '3.8'
services:
  api:
    build:
      context: ./back-end
    ports:
      - "5001:8080"
    command: php -S 0.0.0.0:8080 public/index.php
    depends_on:
      - db

  app:
    build:
      context: ./front-end
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5003:80"
    depends_on:
      - api

  db:
    image: postgres:13
    env_file:
      - ./back-end/.env
    volumes:
      - ./docker/postgres/entrypoints/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - eae-data:/pgdata
    ports:
      - "5002:5432"

volumes:
  eae-data:
    external: true
